### ISSUE TITLE
Putty 0.81 release to fix CVE-2024-31497

### ISSUE THREAD

**Issue by miukumac** [NoMoreFood/putty-cac#126]
Hi, 

Just to bring up that Putty just released 0.81 which fixes the vulnerability detailed in the CVE article where a malicious server operator can, with enough connections, form the private key from the user.

Might want to rebuild against it ASAP.

**Comment by miukumac** [comment]
Saw binaries in the bin directory, not in releases. Sorry for the unneeded ticket!

**Comment by jonkloske** [comment]
Technically it's still listed as prerelease instead of latest, so things may change. I think this is probably worth having until it's listed as latest - currently, the tagged latest version contains the vulnerability.

**Comment by NoMoreFood** [comment]
Yeah, I would really appreciate some testers.  I just like to give it some time to bake before I officially call it released. Given the UI elements and hardware token interactions, I don't have a good automated testing pipeline... I depend on you all :-)

**Comment by jonkloske** [comment]
Ahh, well not sure if this is relevant or not, but I installed the prerelease version and it nuked all my pinned sessions and icon links. I had to repin and connect at least once before all the pinned connections came back. Could be windows, could be the installer. Not a huge issue, but otherwise it's been working fine (modulo my other issue report that's unrelated to this specific version).
