### ISSUE TITLE
Making Pageant automatically load certs on startup

### ISSUE THREAD

**Issue by dprothero** [NoMoreFood/putty-cac#13]
According to the Pageant docs, you can pass filenames to keys to have them preloaded.

How can you preload CAPI certs? Possible?

**Comment by NoMoreFood** [comment]
To preload specific CAPI certificates, all you need to do is identify the certificates using the CAPI:<thumbprint> format as an argument to Pageant.  This can repeated multiple times in order to load multiple certificates.  The thumbprint can be found at the end of the keystring that PuTTY will generate for you or can be found in the certificate details.  

For example,

"C:\Program Files\PuTTY\pageant.exe" CAPI:2a361e0c4c53e9f357207b48d9e4762e3a840521

Please close this issue if this answers your question.

**Comment by NoMoreFood** [comment]
Question answered.  Closing.
