### ISSUE TITLE
Built-in support for Yubikeys

### ISSUE THREAD

**Issue by KamiZavage** [NoMoreFood/putty-cac#15]
After lots of trying I finally found a way to use my Yubikey paired with Putty-CAC.
Though there are 2 programs in between. One of them being OpenSC, which in turn seems to need Yubico-PIV-Manager (which loads the certificate into Windows certmanager where it can be read by OpenSC as pkcs-11).
Is there a way to simply start Pageant.exe and import the Yubikey without having to initialize the Yubico-PIV-Manager as well as OpenSC beforehand?
Thanks in advance once more!

**Comment by NoMoreFood** [comment]
You can use any token with PuTTY CAC provided that a) the token has a  Windows mini-driver and the certificates on the token have been imported into the Windows certificate store (usually Windows does this automatically) or b) The token provides a PKCS DLL driver (which enumerates the certificates on the card directly so no import is required).  

I'll have to defer to other users who are more familiar with Yubikey to validate that you're operating in the most ideal way.  Since Yubikey is definitely popular, I would certainly consider modifying the code to accommodate it better if we can identify the best way to do so.
