### ISSUE TITLE
Pageant won't load certificate again once Smartcard is re-injected

### ISSUE THREAD

**Issue by KamiZavage** [NoMoreFood/putty-cac#21]
Using pageant with a smartcard is not a problem in the first place (i'm using a Yubikey 4 Nano), but if you unplug said smartcard and plug it back in, pageant seems to be unable to load the certificate.
After Just replugging it and startig a PuTTY-CAC session with PKCS Auth, i get an error saying "Server refused public-key signature despite accepting key!".
So I removed the "obsolete" PKCS Key by clicking on it and then hitting "remove" in pageant, then I added it again. But still, trying to authenticate with a server failed. To make pageant work again I need to restart the whole application. This problem seems to be only present on Windows 8 / Windows 10! Is there a way to just automatically remove the PKCS Key once the smartcard is unplugged? I think unplugging said device is not a rarity when you're at your workplace, thus restarting pageant each time does produce a lot of hassle.

Also: The PIN prompt only happens when connecting to a server using putty. Should it not instead prompt you for the PIN just as you add your PKCS cert? Because of that I need to firstly start a PuTTY remote login (on any host) and THEN I can start my WinSCP (which is able to use pageant but does not prompt for a pin if it's needed).

Thanks in advance.

**Comment by lars18th** [comment]
Hi @KamiZavage ,

What you explain has sense. However...

> Is there a way to just automatically remove the PKCS Key once the smartcard is unplugged?

I feel it's not easy to get the message from the OS about the card is unplugged. So, I suggest as a workaround to add some timeout for _retesting_ about the availability of the smartcard. More or less a simple poolling after X seconds.

> Should it not instead prompt you for the PIN just as you add your PKCS cert?

This is too a great idea!

**Comment by NoMoreFood** [comment]
I'm unable to produce this with two other PKCS libraries.

My guess is this is due to a bug in your PKCS library.  Pageant keeps the selected PKCS library loaded in memory after its first use, but whenever it talks to the card, it establishes a fresh connection to the card and then closes the connection to the card when its done.  In principal, Pageant doesn't know or care that your card has been removed.  My guess is the PKCS library itself must cache some information globally and those fresh connections are attempting to use some invalid cache that the PKCS library is maintaining in memory.

**Comment by KamiZavage** [comment]
Which PKCS libraries were you using? Problems occured on Windows 8.1 & 10 with OpenSC.

Also, can you add a button in pageant to force a PIN check so I can activate the certificate without having to use PuTTY just so I am able to use WinSCP? :-)

**Comment by KamiZavage** [comment]
Which PKCS libraries were you using? Problems occured on Windows 8.1 & 10 with OpenSC.

Also, can you add a button in pageant to force a PIN check so I can activate the certificate without having to use PuTTY just so I am able to use WinSCP? :-)

**Comment by NoMoreFood** [comment]
@KamiZavage I used a Gemalto card with a Gemalto PKCS library and a Certum card with Certum PKCS driver.  Neither has the problem you describe.  Have you tried OpenSC with other tokens?  My inclination would be to fix the OpenSC PKCS library.

**Comment by KamiZavage** [comment]
What about the PIN check?
Or is there already a "workaround"?

**Comment by NoMoreFood** [comment]
@KamiZavage I'm confused about what you're actually looking for on the forced PIN check and further confused about how PuTTY needs to be used in order for Pageant to work.  Pageant + WinSCP work just fine without bring PuTTY into the picture.

**Comment by bluikko** [comment]
I have seen the error listed in the OP on "Yubikey Neo", but ~randomly and when using CAPI. It may be related to suspend/hibernate+removal/re-instertion and only occurs very rarely so it has been difficult to track down.

**Comment by KamiZavage** [comment]
@NoMoreFood 
1. You load a certificate into Pageant
2. You start WinSCP
3. You can not connect due to not receiving a PIN check ( <--- Problem!)
4. You start PuTTY-CAC
5. You try to connect to any host
6. You get a PIN prompt, the Certificate can now be used
7. You start WinSCP again and can now connect.

**Comment by NoMoreFood** [comment]
@KamiZavage Does thing happen every time you start Pageant fresh or just after a re-insert operation?  How the PIN prompt works is that the PKCS library is solicited for an accessible private key object.  If that private key object is found, it tries to use it for signing operations. If it is not found, then Pageant/PuTTY presents a PIN prompt.  We don't do a forced PIN check every time because alot of people enjoy the convenience of PIN caching that the library facilitates.  It is disturbing that WinSCP behaves different with PuTTY-CAC so I'm interesting in exploring that if we can get enough information assembled to reproduce the problem.

**Comment by KamiZavage** [comment]
@NoMoreFood Putty-CAC's Pageant just has no PIN prompt. You can not use WinSCP if you have not opened a Putty Connection beforehand!
Look: You want to use WinSCP with your PKCS library, of course. If you just start Pageant, add your PKCS-Cert and start WinSCP right afterwards: *Authentication fails because there was no PIN prompt.*
If you want to use WinSCP you *HAVE* to start a Putty-CAC connection *only for the PIN prompt*, because the key is solely usable after the prompt.

**Comment by NoMoreFood** [comment]
@KamiZavage No need for "yelling".  Your statement is just not universally true --- there are lots and lots of people using PuTTY CAC successfully exactly in the way you describe; I am one of them.   There is probably something specific about the OpenSC libraries you are using and my guess is that the bad behavior is caused by the way that the PuTTY upstream code is trying to limit the DLL search path.  I can look into this, but please indicate the exact PKCS library you are using (please probably a URL to the downloadable file).  Thanks.

**Comment by KamiZavage** [comment]
I'm sorry, that wasn't meant to be a yell.
Problem caused using OpenSC-0.17.0-win64-vs12.
As stated, WinSCP connects, tries authentication, starts Authentication with public key from agent but is stuck at that point. No PIN prompted.

(You can get that Version of OpenSC here: https://github.com/OpenSC/OpenSC/releases/download/0.17.0/OpenSC-0.17.0-win64_vs12-Release.msi )

**Comment by NoMoreFood** [comment]
@KamiZavage I'm looking into OpenSC now.  I can't reproduce the issue with my OpenSC "supported" card, but it's not a Yubikey so I'm not sure how different the code paths are.  How many certificates do you have on your Yubikey?  Can you confirm that the same certificate thumbprint is being display on the screen when starting with PuTTY+Pageant that makes it all work?

I may have to send you a special version with some debug lines included to track this down further.

**Comment by KamiZavage** [comment]
Hi, Sorry for the late answer.
I have just one certificate on it (generated with yubico piv tool).
I'd be glad to help you testing and stuff!

**Comment by KamiZavage** [comment]
(Also, I am back from vacation :D)

**Comment by dinhngtu** [comment]
Does CAPI mode work with your Yubikey? Normally there would be no need to use PKCS for Yubikeys.

**Comment by dinhngtu** [comment]
Do you see your keys in the Yubikey PIV Manager? If yes, then they should
also be available in the Certificates MMC snap-in, and selectable in the
CAPI cert section of PuTTY-CAC.

**Comment by KamiZavage** [comment]
It surely is selectable from the MMC but what is the difference in using CAPI or PKCS in this case?

**Comment by dinhngtu** [comment]
I figured since PKCS is buggy, you might want to try CAPI since it's been
quite reliable for me.

**Comment by KamiZavage** [comment]
For me it's the other way round.
I have no clue why there is no PIN prompt when using CAPI. My Yubikey does not "cooperate" without the correct PIN.

**Comment by NoMoreFood** [comment]
@KamiZavage Did you create the public/private keypair on your card directly or did you import it? Wonder if you have something weird going on like a duplicate public key entry on token without a matching a certificate associated with the one of the public keys.

**Comment by KamiZavage** [comment]
@NoMoreFood the keypair was created directly on the card using the yubico-piv-tool

**Comment by NoMoreFood** [comment]
@KamiZavage Is this still a problem?  Just realized this was still sitting as an open issue.
