### ISSUE TITLE
Suggestion: Pageant supporting key usage confirmation

### ISSUE THREAD

**Issue by lars18th** [NoMoreFood/putty-cac#22]
Hi,

This function described in the title is present in some other forks. And I feel it very useful. It's a check for knowing wich certificate is used, and a method for grant the use.

The original patch is published here:
http://people.mpi-klsb.mpg.de/~pcernko/pageant.html

And in this forum is commented the port to another fork that uses some PuTTY-CAC patches:
http://www.9bis.net/kitty/?action=forum&id=0809

I hope you can implement (importing the patches) it soon!
Regards.

**Comment by NoMoreFood** [comment]
I actually like this feature alot -- I always considered it a "vulnerability" of sorts that anything could potentially hijack a cached Pageant key just by asking for it.  However, it really doesn't have to do with certificates --- it can be generically applied to any PuTTY key.  I'll consider it.

**Comment by bluikko** [comment]
This feature (activity indicator at least) would be really great to see.

My personal, outside commentator, opinion is that this should probably be integrated upstream since there are open feasible wishes for these features.

The relevant wishes are:
https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/pageant-key-confirm.html
https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/pageant-activity-ind.html

The latter is listed as "fun"/"low" difficulty/priority vs. "tricky"/"medium" for the former.

If there really are development resources to do this, why not start with the indicator (if it is truly so easy) and try to push it upstream? Are there issues in getting changes to the upstream? Or has KiTTY implemented the features in a way that is unacceptable for upstream?

**Comment by lars18th** [comment]
Hi @bluikko ,

The problem with the upstream it's that the code needs to be fully portable. And the main developer only likes to focus on functionality, and not the UI.

Futhermore, other PuTTY forks have this implemented (for example, KiTTY) and the source is available. So my suggestion it's review the examples, and implement (or copy with permission) inside PuTTY-CAC. I feel (I'm not sure) that the changes aren't huge, so it can be integrated without much effort.

I hope @NoMoreFood agree with my sugggestion. :smile: 
Regards!

**Comment by bluikko** [comment]
@lars18th That makes sense. Thanks for the explanation.

**Comment by NoMoreFood** [comment]
The patch will not work work with ECDSA keys.  However, I will look into something similar in the next month.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

> The patch will not work work with ECDSA keys. However, I will look into something similar in the next month.

Great to hear it. :smile: 
Try to use the source code used in the other fork described above. I feel is uptodate.

**Comment by NoMoreFood** [comment]
Please try this and see how it works for you.  It's a new option in the system tray menu:

[puttycac-64bit-0.70u4-beta.zip](https://github.com/NoMoreFood/putty-cac/files/1865839/puttycac-64bit-0.70u4-beta.zip)

**Comment by bluikko** [comment]
Works great.

But at least on my Win7 with no DPI/HiRes changes for the screen the confirmation dialog is quite large. Obviously this is and the following suggestions are not important issues.

I would also suggest adding "Pageant" somewhere on the dialog title, perhaps " - Pageant" at the end of the title so it would follow the standard Microsoft guidelines.

Further UI/usability tweaks, the "Esc" keyboard button could map to the "No" answer.

**Comment by NoMoreFood** [comment]
I'll add '- Pageant' to the title.  

We use the builtin MessageBox() function so I don't think there's much I can do about the DPI issue.  The only way I can change the 'Esc' option is to change it to an 'Ok' / 'Cancel' dialog but I think that makes the choice less clear.

**Comment by bluikko** [comment]
Found one bug (or is it just unfinished? sorry if it is, no such comments in the commit), in commit 437c2c6b126be96f7add5dedf6606fc5be18880b it states "Added system tray menu option" but it does not work:
When I start Pageant, the menu option is unchecked. But cert prompting does happen. If I click the menu option to enable, it will be impossible to uncheck/disable the option (clicking on it does nothing).

Other options such as force PIN caching do work.

**Comment by NoMoreFood** [comment]
That was indeed a bug.  Please try this: [puttycac-64bit-0.70u4-beta2.zip](https://github.com/NoMoreFood/putty-cac/files/1867080/puttycac-64bit-0.70u4-beta2.zip)

**Comment by bluikko** [comment]
Now it works as expected.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

Using last "release version" (0.70 Update 4)...

![putty-cac](https://user-images.githubusercontent.com/9989964/38239205-593dc272-372c-11e8-8384-caa988f740e0.png)

So the option "Cert Auth Prompting" is enabled, but I don't see **any** message when a certificate is used!
What's the expected behaviour with this new function enabled?

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

I review the code (commit https://github.com/NoMoreFood/putty-cac/commit/437c2c6b126be96f7add5dedf6606fc5be18880b) and I don't know why I don't see any Modal Window when the certificate is used. I'll investigate more. :disappointed: 

However, I don't see in the code any reference to the "Ballon Message" when a certificate is used. See my previous image in the initial request:

![key-notification](https://user-images.githubusercontent.com/9989964/35216813-382beeb0-ff69-11e7-8635-b303deaf29ad.jpg)

I feel that with current code, only one Modal Window request to the user to "Accept" or "Reject" the use of the Certificate is used. But, the "Ballon Message" is a simple message when _a certificate is used_. This is a different functionality. You can mix or not it with the request of the certificate. And it is a simple warning of the use of a certificate. So, you can have all four user-cases: Acceptance disabled, and Use disabled (default behaviour); Acceptance enabled, and Use disabled (the mode that you have now implemented); Acceptance disabled, and Use enabled (automatically use all certificates, but warn the user each time a certificate is used); and Acceptance enabled, and Use enabled (it seems that it has no sense, but if sometime you will implement some caching acceptence, then it will have sense).

I hope you can agree to consider also this enhancement.
Regards.

**Comment by lars18th** [comment]
Hi @NoMoreFood ,

I see the confusion!
You only request the acceptance of the Key when using CAPI or PKCS certificates, and __not__ when using PuTTY keys. Why not? I don't see any difference... Please, adapt the code to ask for the acceptance or _any_ kind of keys. I don't see any advantage using it only for SmartCards, even when with a SC you have the PIN confirmation enabled.

Futhermore, why you request to use the Certificate _after_ typing the PIN of the card? I feel it has more sense to request it _before_. Don't you think so?

**Comment by NoMoreFood** [comment]
You're correct on prompting before the signing operation. I'll move that.  

The reason for not doing it with other PuTTY keys is because this is a certificate-centric fork, and there was a good spot in my code to put the change.  Injecting more code in random spots jeopardizes my ability to effectively maintain this fork in my freetime.  Remember, I don't get paid for this ;-).

**Comment by lars18th** [comment]
> You're correct on prompting before the signing operation. I'll move that.

Great! :smile: 

> The reason for not doing it with other PuTTY keys is because this is a certificate-centric fork, and there was a good spot in my code to put the change. Injecting more code in random spots jeopardizes my ability to effectively maintain this fork in my freetime

OK. But the code isn't the same? I feel you only need to do a minimal modification to support it. From my point of view, it has no sense to ask only for SC Certificates and not for all keys!
I hope you reconsider it.

> Remember, I don't get paid for this ;-).

I feel you say this because my request for the "Useage Warning Message", right?
I'm only presenting here my comments and suggestions... with the idea to help and improve this project.
Your work is excelent! Please continue working on it as you can.

Regards.

**Comment by NoMoreFood** [comment]
The auth prompt has been moved before the PIN prompt in the latest update to the pre-release.  I also squashed the most recent commits down to one (in case you're looking). 

> I feel you say this because my request for the "Useage Warning Message", right?
I'm only presenting here my comments and suggestions... with the idea to help and improve this project.

I definitely appreciate your suggestions, but I have to balance the intrusiveness of the changes with the time I have to work on them.  If the next version of PuTTY comes along and they make tons of changes, I've got to figure out how to merge in the PuTTY CAC functions.  By localizing this change to certificates, this feature was very simple to integrate.  Also, on some level there is a matter of mission: this fork is about providing certificate-based support to PuTTY.  It's not about general enhancements to PuTTY.  If want to improve PuTTY, I'd rewrite it entirely because the code is actually pretty terrible.  It could be written in less than 50% of the code if it used modern practices, patterns, and language features.

**Comment by lars18th** [comment]
> The auth prompt has been moved before the PIN prompt in the latest update to the pre-release.

Tested and working. Thank you! :+1: 

> I definitely appreciate your suggestions, but ...

I only like to collaborate. And I understand and I accept your opinion.
In any case: You really find it's hard to request the confirmation window for both, certificates and keys?
I ask this question with all due respect!
For me it's very annoying (and useless) to not have this option enabled for both. Why? Because I can run _only_ one Pageant in my machine. Then I can't use another fork of PuTTY-Pageant that has this option enabled for keys, and PuTTY-CAC for certificates.

I hope you can reconsider it, please.

Or if you prefer: What about supporting PuTTY-CAC-Pageant running in "_Client_ Mode"? In this case, I can run another Pageant as the main agent, and use your PuTTY-CAC Pageant to provide the SmartCard certificates.
The KeeAgent plugin for KeePass has this "Pageant Client Mode" implemented:
https://github.com/dlech/KeeAgent

Regads.

**Comment by NoMoreFood** [comment]
No further work planned on this.
