### ISSUE TITLE
Pageant 0.69 cannot load smartcard certificate

### ISSUE THREAD

**Issue by dinhngtu** [NoMoreFood/putty-cac#3]
I use Pageant with a Yubikey Neo on Windows 10 version 1703. On version 0.69, when starting Pageant and specifying a certificate name as command prompt argument, I get this error (both on the PIN caching version and on the master branch):

![image](https://cloud.githubusercontent.com/assets/1257909/26055887/fcd41262-399c-11e7-8fd4-432f0c363803.png)

Selecting the certificate manually in Pageant doesn't work either.

Also, selecting the certificate in PuTTY works, but on connection the same error is displayed. Clicking "Copy to clipboard" in the Authentication parameters causes PuTTY to crash.

**Comment by NoMoreFood** [comment]
@dinhngtu.  Thanks, this helps narrow down the issue some folks have been seeing.  Something is probably going wrong when looking up the certificate using the sha1 thumbprint in cert_capi_load_cert() or cert_capi_get_cert_store() within the [source](https://github.com/NoMoreFood/putty-cac/blob/master/cert/cert_capi.c).   I'll take a look tonight.  

Few questions / requests:

1) Is the certificate selectable using the 'Set CAPI Cert...' button?
2) I imagine that the 'View Certificate' option also fails / causes PuTTY to crash?
3) Is the certificate thumbprint algorithm list as sha1 under the certificate details?
4) If you're comfortable (and I completely understand if you're not), can you send me your public .cer file for the cert you are trying to use?  (berns@uwalumni.com)

**Comment by dinhngtu** [comment]
I found two interesting things in the code:

- Puttycac 0.68 expects full certificate path in the command line, including the cert store name (e.g. "CAPI:User\MY\hashhashhash"). Puttycac 0.69 assumes that the cert name is of the form "CAPI:hashhashhash", so Pageant can't load the correct certificate.
- Puttycac uses CERT_SIGN_HASH_CNG_ALG_PROP_ID to detect the certificate type; however, it provides the key type of the signer CA instead of the subject. In my case I have a RSA public key signed using an ECDSA certificate authority, so Pageant mistakes my certificate as an ECDSA certificate. You probably want CERT_PUB_KEY_CNG_ALG_BIT_LENGTH_PROP_ID instead.

Back to your questions:

1. Yes
2. No
3. Yes
4. Sent

**Comment by NoMoreFood** [comment]
@dinhngtu  Awesome feedback.  I will take a look tonight.

**Comment by NoMoreFood** [comment]
@dinhngtu Please see if the link below works better.  I was able to use the algorithm identifier from the certificate context structure.  Hopefully that works better.  I believe i've also got the command line loading fixed up.

[puttycac-pincaching-rev2.zip](https://github.com/NoMoreFood/putty-cac/files/1002905/puttycac-pincaching-rev2.zip)

**Comment by dinhngtu** [comment]
Thanks for the work.

I suggest adding a call to cert_convert_legacy() in pageant_add_keyfile(). With this change, loading and using certificates works. However, PIN caching doesn't work yet.

**Comment by NoMoreFood** [comment]
@dinhngtu Thanks for the help.   Per your suggestion, do you know which call within pageant_add_keyfile() is dereferencing the filename?  The only downstream calls are key_type() and ssh2_userkey_loadpub() which already call cert_convert_legacy() internally.  

Thank you very much for the help.  If you have any insights on the PIN caching, I'd appreciate it.  It's proven hard to track this down without being any to reproduce it.

**Comment by dinhngtu** [comment]
Actually, disregard that. I made a mistake with the command line parameter. The code as it is works.

I will look at the PIN caching once I have some time. Could you give me a short summary on how the PIN caching code works?

**Comment by NoMoreFood** [comment]
Sounds good.  It's pretty simple.  If the Pageant PIN caching is enabled via the system tray, cert_cache_enabled(-1) will return TRUE when called from cert_capi_sign().   If cert_cache_enabled(-1) returns TRUE, the code calls cert_pin() which will check an internal (static) linked list that will immediately return the requested PIN if it is already in the list.  If it's not in the list, it'll pop a credential for the user to enter the PIN.   After this, the cert_capi_sign() will attempt to manually enter the PIN for the user by calling CryptSetProvParam() prior to signing the hash via CryptSignHash() which is what normally produces the PIN prompt.  When I do this on my computer, CryptSignHash() no longer pops a credential prompt but it would appear that it is still popping creds on your computer and others else who have tested.  

This could be evidence that CryptSetProvParam() is failing in the same way that built-in PIN caching is failing after the KB update in March.  I would be very curious whether the NCrypt() APIs suffer the same issue, but we're need to change the code to use those for RSA instead of just ECDSA.
