### ISSUE TITLE
windows xp

### ISSUE THREAD

**Issue by exoryna** [NoMoreFood/putty-cac#37]
Is it compatibile with Windows XP with SP3 ?

**Comment by NoMoreFood** [comment]
It is not compiled with XP compatibility support set in Visual Studio and I believe certain functions are not available in XP.  It may work and you're welcome to try it out, but it is not released with Windows XP compatibility in mind.  Most users and organizations using PuTTY CAC are doing so because of the cybersecurity benefits so supporting operating systems outside of extended support lifetime is not something of immediate focus.
