### ISSUE TITLE
Putty-cac has a blurry screen on launch

### ISSUE THREAD

**Issue by justchris1** [NoMoreFood/putty-cac#40]
I am on Windows 10 machine with a 4K monitor and I have just discovered putty-cac.  However, it looks blurry.  Putty 0.70 doesn't have this issue and when I launch both side by side, the difference is amazing.  After trying to use for a few hours, I started to get a headache.  I tried playing with compatibility settings, but to no avail.  Any recommendations as to what could be the cause if they are off the same codebase?  (Screenshot shows putty on left and putty-cac on right)

![putty vs putty cac](https://user-images.githubusercontent.com/30219018/53290391-403bbe00-3771-11e9-8441-2903f59cf9ae.JPG)

**Comment by NoMoreFood** [comment]
This is interesting.  I actually see the opposite on my monitor -- regular PuTTY is blurry and PuTTY CAC is clearer.  I will have to see what is driving this different in behavior.

**Comment by NoMoreFood** [comment]
I found the issue at a high-level.  The manifest in the resource file is not getting applied properly.  My guess is this is due to some nuance on how Visual Studio 2017 behaves.   I'll have a binary for you to test tomorrow.

**Comment by NoMoreFood** [comment]
Please try this https://github.com/NoMoreFood/putty-cac/blob/master/binaries/puttycac-0.70u7.zip (32-bit) or this https://github.com/NoMoreFood/putty-cac/blob/master/binaries/puttycac-64bit-0.70u7.zip (64-bit) and let me know if this corrects the issue.

The core issue appears to be due to the fact that the original builds were setup for the UK and I'm building in the US which resulted in two manifests in the executable.  The US one was missing the settings for DPI awareness.  I also added in a new setting to allow GDI scaling which fixed the blurriness on my 2K monitor when the DPI awareness is being used.

**Comment by justchris1** [comment]
Thanks for the quick reply - I appreciate you trying to help out here.  I gave it a whirl, and it is definitely better, but it still has something different that is still causing blur.  The first screenshot is near what I sent in yesterday.  The text on your new release now seems pretty clear, even though it seems a bit bigger.  The screen definitely is of good enough quality to use on the setup screen.  I intentionally selected this screen I took the screenshot on so you can see the color selections are the same.  I also validated that the appearance is the same, including the font and font size.

The second screenshot you can see what it looks like in the console after login.  Hopefully you can see it is still duller and more blurry.  The screen also is a different size, which is still odd since everything should be the 'same'.  I don't really care is the screen is a different size though, as long as it is clear.   Thanks for your help!

![putty vs putty cac2](https://user-images.githubusercontent.com/30219018/53301415-90be2480-3820-11e9-808b-da04ef8abd3f.JPG)

<img width="992" alt="putty vs putty cac3" src="https://user-images.githubusercontent.com/30219018/53301416-91ef5180-3820-11e9-9355-1f33767ae073.PNG">

**Comment by justchris1** [comment]
A few other details: My screen is 3840x2160 and I run at 150% scaling on the windows 10 display settings, if that helps.

**Comment by NoMoreFood** [comment]
What operating system are you running?  If Windows 10, which build?

**Comment by NoMoreFood** [comment]
So I confirmed this is due to GDI scaling and according to the experts at Microsoft, the text on the left is supposed to clearer -- and it does look alot better on my 2K monitor than normal PuTTY (which doesn't have GDI scaling turned on).  On my 4K monitor, I can see the same results you do.  Basically what's going on is that instead of graphics subsystem rendering the text using the original font and then blowing it up, it's rendering the text using a larger font based on your DPI settings.  I think what you're seeing is the additional "smoothness" you get a result of using a more accurate font.  Not sure --- I keep going back and forth on which one I like more.

**Comment by NoMoreFood** [comment]
Alright, I convinced myself to leave GDI scaling off.  Please try the aforementioned zip files again.

**Comment by justchris1** [comment]
That looks great!  Thanks for the help.
