### ISSUE TITLE
windows 10 with ActivClient does not show certificate selection window

### ISSUE THREAD

**Issue by k3it** [NoMoreFood/putty-cac#6]
There seems to be a problem under windows 10 with ActivClient in cert enumeration function.  It brings up a partial window but hangs w/o showing the list of available certificates, both for putty and pageant.

We were able to work around this by hard coding the certificate path in the command line for pageant.  unfortunately I don't have access to this machine anymore.  A user took off with it since he was ok with the workaround..  Just thought I should report this..

**Comment by NoMoreFood** [comment]
It's possible this is due to the "improvements" the upstream made in the DLL anti-hijacking code.  I don't have a copy of ActivClient that works on Windows 10 so I think the best I can do is compile a version with the anti-hijacking code turned off for you to test if you are willing to try it.  If it is the problem, then maybe the best route is to provide a registry setting to disable the anti-hijacking stuff or just turn it off altogether.

**Comment by NoMoreFood** [comment]
@k3it Can you confirm which version of ActivClient you are using?  Have you tried with both the 32-bit and 64-bit version of PuTTY / Pageant?

**Comment by k3it** [comment]
I have tried a couple of different recent releases of putty-cac (all 64 bit) and they all had trouble with listing the certs on Win10.  ActivClient v6.2.0.168.

**Comment by NoMoreFood** [comment]
@k3it Okay, good to know.   It may be worth trying the 32-bit version (which runs fine on a 64-bit OS) since I have a report from another user that it might address this issue.  That'd only be a workaround, but it would be interesting to know if you see the same thing.  It would also be good to see if the ActivClient 6.2.0.212 patch works for you.

**Comment by NoMoreFood** [comment]
@k3it On a potentially related note, I tried using the ActivClient PKCS DLLs using ActivClient 6.2.0.212 on Windows 10 instead of CAPI.  The 64-bit PKCS11 DLL for my ActivClient 6.2 installation on Windows 10 does not return any certificates whereas the 32-bit DLL does regardless of the DLL anti-hijacking code being active.  In short, it appears that the ActivClient 64-Bit PKCS DLL has a bug.  Since I don't believe ActivClient 6.2 is even officially supported on Windows 8 much less Windows 10, there may be no good resolution to that particular issue.  Per my previous comment, I'm still curious whether you seeing issues with CAPI on 32-bit PuTTY CAC and/or ActivClient 6.2.0.212 though since I'm unable to reproduce the CAPI issue.

**Comment by k3it** [comment]
Bryan, sorry for not responding quickly. I'm trying to catch the user with that special Win10 machine. It will be next week probably.  I will test the 32 bit version as well as the new binaries.  Thanks very much for keeping an eye on this.

**Comment by NoMoreFood** [comment]
@k3it I think we may have had a breakthrough.  If you could try the binaries here, that'd be great:

https://github.com/NoMoreFood/putty-cac/tree/master/binaries

**Comment by k3it** [comment]
The last set of binaries worked perfectly fine. No issues with cert selection in both pageant and putty . Thank you

**Comment by NoMoreFood** [comment]
Corrected in release PuTTY CAC 0.70 Update #1.
