### ISSUE TITLE
RFC6187 / X.509v3 support?

### ISSUE THREAD

**Issue by bluikko** [NoMoreFood/putty-cac#9]
This might be a stupid question - but putty-cac does not support RFC6187 ("x509v3*") does it, and instead uses only pubkey method even if certificate is loaded from CAPI?

Since the only open implementation seems to be PKIX-SSH I guess implementing RFC6187 is too much of a nightmare?

**Comment by NoMoreFood** [comment]
You are correct it does not currently support those x509v3-* methods.  I'm not overly familiar with the RFC6187 specification so I'll have to read through it thoroughly, but at a glance it looks like it would be a rather intrusive change since PuTTY CAC relies heavily on the PuTTY code to handle most of the supported public key algorithms and just defers the public key signing part over to the PuTTY CAC code.

**Comment by NoMoreFood** [comment]
After further review and consideration of the necessary changes to other PuTTY functions, I have no plans to accommodate this, sorry.
